version: '3.2'
services: 
  mongo:
    image: mongo
    restart: always
    env_file: ./api/.env      
    ports:
      - "27017:27017"
    volumes: 
      - 'db_volume:/data/db'

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    env_file: ./api/.env      
  api:
    build: ./api
    depends_on:
      - mongo
    env_file: ./api/.env
    ports:
      - '3031:3031'
    command: npm run dev
    volumes:
      - ./api:/api/
      -  /api/node_modules
  fe:
    build: ./frontend
    environment:
       - CHOKIDAR_USEPOLLING=true
    env_file: ./frontend/.env
    ports:
      - '3000:3000'
    command: npm start
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
volumes:
  db_volume:
    driver: local